export default {
  tertiaries: [
    {
      _id: '1',
      image: './varsity-logos/uj-logo.png',
      name: 'University of Johannesburg',
      shortName: 'UJ',
      province: 'Gauteng',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '2',
      image: './varsity-logos/northwest-logo.png',
      name: 'University of Northwest',
      shortName: 'UNW',
      province: 'North West',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '3',
      image: './varsity-logos/uni pre-logo.png',
      name: 'University of Pretoria',
      shortName: 'UP',
      province: 'Gauteng',
      link: 'https://www.up.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '4',
      image: './varsity-logos/wits-logo.png',
      name: 'University of Witswatersrand',
      shortName: 'Wits',
      province: 'Gauteng',
      link: 'https://www.wits.ac.za/study-at-wits/',
      numberOfStudents: '1000',
    },
    {
      _id: '5',
      image: './varsity-logos/KZN-logo.png',
      name: 'University of KWAZULU_NATAL',
      shortName: 'UKZ',
      province: 'Kwazulu-Natal',
      resize: 'resize-class',
      link: 'https://www.ukzn.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '6',
      image: './varsity-logos/CPUT-logo.png',
      name: 'Cape Peninsula University of Technology',
      shortName: 'CPUT',
      province: 'Cape Town',
      resize: 'resize-class',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '7',
      image: './varsity-logos/CUT-logo.png',
      name: 'Central University of Technology',
      shortName: 'CUT',
      province: 'Bloemfontein',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '8',
      image: './varsity-logos/DUT-logo.png',
      name: 'Durban University of Technology',
      shortName: 'DUT',
      province: 'Durban and Pietermaritzburg',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '9',
      image: './varsity-logos/UF-logo.png',
      name: 'University of the Free State',
      shortName: 'UF',
      province: 'Free State',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '10',
      image: './varsity-logos/MUT-logo.png',
      name: 'Mangosuthu University of Technology',
      shortName: 'MUT',
      province: 'Umlazi, Durban',
      link: 'https://www.nwu.ac.za',
      resize: 'resize-class',
      numberOfStudents: '1000',
    },
    {
      _id: '11',
      image: './varsity-logos/Rhode-logo.png',
      name: 'Rhodes University',
      shortName: 'RU',
      province: 'Grahamstown',

      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '12',
      image: './varsity-logos/SMU-logo.png',
      name: 'Sefako Makgatho Health Sciences University',
      shortName: 'SMU',
      province: 'Pretoria',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '13',
      image: './varsity-logos/SPU-logo.png',
      name: 'Sol Plaatje University',
      shortName: 'SU',
      province: 'Kimberley',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '14',
      image: './varsity-logos/TUT-logo.png',
      name: 'Tshwane University of Technology',
      shortName: 'TUT',
      province: 'Pretoria, Limpopo',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '15',
      image: './varsity-logos/UCT-logo.png',
      name: 'University of Cape Town',
      shortName: 'UCT',
      province: 'Cape Town',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '16',
      image: './varsity-logos/UFH-logo.png',
      name: 'University of Fort Hare',
      shortName: 'UFH',
      province: 'Alice and East London',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '17',
      image: './varsity-logos/UNISA-logo.png',
      name: 'Durban University of Technology',
      shortName: 'DUT',
      province: 'Durban and Pietermaritzburg',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '18',
      image: './varsity-logos/UniZulu-logo.png',
      name: 'University of Zululand',
      shortName: 'UZ',
      province: 'Empangeni',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '19',
      image: './varsity-logos/UOL-logo.png',
      name: 'University of Limpopo',
      shortName: 'UL',
      province: 'Turfloop',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '20',
      image: './varsity-logos/UOV-logo.png',
      name: 'University of Venda',
      shortName: 'UV',
      province: 'Thohoyando',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '21',
      image: './varsity-logos/UWC-logo.png',
      name: 'University of the Western Cape',
      shortName: 'UWC',
      province: 'Tygerberg, Cape Town',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '22',
      image: './varsity-logos/VUT-logo.png',
      name: 'Vaal University of Technology',
      shortName: 'VUT',
      province: 'Johannesburg',
      link: 'https://www.uj.ac.za',
      resize: 'resize-class',
      numberOfStudents: '1000',
    },
    {
      _id: '23',
      image: './varsity-logos/WSU-logo.png',
      name: 'Walter Sisulu University',
      shortName: 'WSU',
      province: 'East London and Mthatha',
      resize: 'resize-class',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '24',
      image: './varsity-logos/US-logo.png',
      name: 'University of Stellenbosch',
      shortName: 'US',
      province: 'Stellenbosch',
      size: 'size',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '25',
      image: './varsity-logos/UM-logo.png',
      name: 'University of Mpumalanga',
      shortName: 'UM',
      province: 'Mbombela',
      size: 'size',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '26',
      image: './varsity-logos/NMU-logo.png',
      name: 'Nelson Mandela Metropolitan University',
      shortName: 'NMU',
      province: 'Port Elizabeth and George',
      link: 'https://www.uj.ac.za',
      resize: 'resize-class',
      numberOfStudents: '1000',
    },
    {
      _id: '27',
      image: './IIE-logos/MSA-logo.png',
      name: 'IIE MSA College',
      shortName: 'VUT',
      province: 'Johannesburg',
      link: 'https://www.uj.ac.za',
      resize: 'resize-class',
      numberOfStudents: '1000',
    },
    {
      _id: '28',
      image: './IIE-logos/Rosebank-logo.png',
      name: 'IIE Rosebank College',
      shortName: 'WSU',
      province: 'East London and Mthatha',
      resize: 'resize-class',
      link: 'https://www.nwu.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '29',
      image: './IIE-logos/Varsity-logo.png',
      name: 'IIE Varsity College',
      shortName: 'US',
      province: 'Stellenbosch',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
    {
      _id: '30',
      image: './IIE-logos/Vega-logo.png',
      name: 'IIE Vega College',
      shortName: 'UM',
      province: 'Mbombela',
      resize: 'resize-class',
      link: 'https://www.uj.ac.za',
      numberOfStudents: '1000',
    },
  ],
};
